version: '3.9'
services:
  backend:
    image: 0722_dementia_backend
    build: ../Deementia-backend
    container_name: 0722_DeBackend
    restart: always
    ports:
      - 1902:80
  nginx:
    image: nginx:stable
    container_name: 0722_DeFrontend
    restart: always
    ports:
      - 9001:80
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf